language: python
python:
  - "2.7.10"


before_install:
  - pip install nose2
  - pip install coveralls

install:
  - pip install -r requirements.txt

before_script:
  - export FLASK_APP=run.py
  - export FLASK_CONFIG=testing
  - flask db init
  - flask db migrate
  - flask db upgrade

script:
  - nose2

after_success:
  - coveralls
