language: python
python:
  - "2.7.10"


before_install:
  - pip install nose2

install:
  - pip install -r requirements.txt

before_script:
  - export FLASK_APP=run.py
  - export FLASK_CONFIG=testing
  - export PRODUCTION_DATABASE_URI='None'

script:
  - nose2
